openapi: 3.0.0

info:
  version: '1.0'
  title: 'HireUp Web API'
  description: 'Web Resources Specification (A7) for HireUp'

servers:
  - url: http://localhost:8000
    description: Development server

tags:
  - name: 'M01: Authentication and User Profile'
  - name: 'M02: Job Posting'
  - name: 'M05: Job Applications'
  - name: 'M06: Managers'
  - name: 'M07: User Administration and Static pages'

paths:
  /login:
    get:
      operationId: R101
      summary: 'R101: Login Form'
      description: 'Provide login form. Access: PUB'
      tags:
        - 'M01: Authentication and User Profile'
      responses:
        '200':
          description: 'Ok. Show log-in UI'
    post:
      operationId: R102
      summary: 'R102: Login Action'
      description: 'Processes the login form submission. Access: PUB'
      tags:
        - 'M01: Authentication and User Profile'
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '302':
          description: 'Redirect after processing the login credentials.'
          headers:
            Location:
              schema:
                type: string
              examples:
                302Success:
                  description: 'Successful authentication. Redirect to dashboard.'
                  value: '/dashboard'
                302Error:
                  description: 'Failed authentication. Redirect to login form.'
                  value: '/login'

  /logout:
    post:
      operationId: R103
      summary: 'R103: Logout Action'
      description: 'Logout the current authenticated user. Access: JSK, RCR, MNG, ADM'
      tags:
        - 'M01: Authentication and User Profile'
      responses:
        '302':
          description: 'Redirect after processing logout.'
          headers:
            Location:
              schema:
                type: string
              examples:
                302Success:
                  description: 'Successful logout. Redirect to homepage.'
                  value: '/'

  /register:
    get:
      operationId: R104
      summary: 'R104: Register Form'
      description: 'Provide new user registration form. Access: PUB'
      tags:
        - 'M01: Authentication and User Profile'
      responses:
        '200':
          description: 'Ok. Show sign-up UI'
    post:
      operationId: R105
      summary: 'R105: Register Action'
      description: 'Processes the new user registration form submission. Access: PUB'
      tags:
        - 'M01: Authentication and User Profile'
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                type:
                  type: string
              required:
                - name
                - email
                - password
      responses:
        '302':
          description: 'Redirect after processing the new user information.'
          headers:
            Location:
              schema:
                type: string
              examples:
                302Success:
                  description: 'Successful registration. Redirect to dashboard.'
                  value: '/dashboard'
                302Failure:
                  description: 'Failed registration. Redirect to register form.'
                  value: '/register'

  /job-seeker/{registered_user_id}:
    get:
      operationId: R106
      summary: 'R106: View user profile'
      description: 'Show the individual user profile. Access: JSK, RCR, MNG'
      tags:
        - 'M01: Authentication and User Profile'
      parameters:
        - in: path
          name: registered_user_id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: 'Ok. Show User Profile UI'

  /job-seeker/profile/edit:
    get:
      operationId: R107
      summary: 'R107: Edit Profile Form'
      description: 'Provide form to update user profile. Access: JSK'
      tags:
        - 'M01: Authentication and User Profile'
      responses:
        '200':
          description: 'Ok. Show Edit Profile UI'
  
  /job-seeker/profile/update:
    put:
      operationId: R108
      summary: 'R108: Update Profile Action'
      description: 'Processes profile updates. Access: JSK'
      tags:
        - 'M01: Authentication and User Profile'
      responses:
        '302':
          description: 'Redirect after processing profile update.'
          headers:
            Location:
              schema:
                type: string
              examples:
                302Success:
                  description: 'Successful update. Redirect to profile.'
                  value: '/job-seeker/{registered_user_id}'

  /job-seeker:
    get:
      operationId: R109
      summary: 'R109: Search Job Seekers'
      description: 'List job seekers with filters. Access: JSK, RCR, MNG'
      tags:
        - 'M01: Authentication and User Profile'
      parameters:
        - in: query
          name: q
          schema:
            type: string
      responses:
        '200':
          description: 'Ok. Show Seekers List UI'

  /:
    get:
      operationId: R201
      summary: 'R201: Homepage'
      description: 'Show latest job offers. Access: PUB'
      tags:
        - 'M02: Job Posting'
      responses:
        '200':
          description: 'Ok. Show Homepage UI'

  /job_postings:
    get:
      operationId: R202
      summary: 'R202: Search Jobs'
      description: 'List jobs with search keywords (authenticated index). Access: JSK, RCR, MNG, ADM'
      tags:
        - 'M02: Job Posting'
      parameters:
        - in: query
          name: q
          description: Full text search keywords
          schema:
            type: string
      responses:
        '200':
          description: 'Ok. Show Jobs List UI'

  /job-postings:
    post:
      operationId: R203
      summary: 'R203: Create Job Action'
      description: 'Processes new job creation. Access: RCR'
      tags:
        - 'M02: Job Posting'
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                location:
                  type: string
              required:
                - title
                - description
      responses:
        '302':
          description: 'Redirect after creating job.'
          headers:
            Location:
              schema:
                type: string
              examples:
                302Success:
                  description: 'Successful creation. Redirect to job details.'
                  value: '/job_postings/{jobPosting}'

  /recruiter-dashboard/new-job-posting:
    get:
      operationId: R204
      summary: 'R204: Create Job Form'
      description: 'Provide UI to create a job. Access: RCR'
      tags:
        - 'M02: Job Posting'
      responses:
        '200':
          description: 'Ok. Show Create Job UI'

  /job_postings/{jobPosting}:
    get:
      operationId: R205
      summary: 'R205: Job Details'
      description: 'Show job info. Access: JSK, RCR, MNG, ADM'
      tags:
        - 'M02: Job Posting'
      parameters:
        - in: path
          name: jobPosting
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 'Ok. Show Job UI'

  /job-postings/{job_posting}:
    delete:
      operationId: R206
      summary: 'R206: Delete Job Action'
      description: 'Remove a job posting. Access: RCR'
      tags:
        - 'M02: Job Posting'
      parameters:
        - in: path
          name: job_posting
          required: true
          schema:
            type: integer
      responses:
        '302':
          description: 'Redirect after deleting job.'
          headers:
            Location:
              schema:
                type: string
              examples:
                302Success:
                  description: 'Successful deletion. Redirect to jobs list.'
                  value: '/job_postings'

  /job-postings/{job_posting}/edit:
    get:
      operationId: R207
      summary: 'R207: Edit Job Form'
      description: 'Provide UI to edit an existing job. Access: RCR'
      tags:
        - 'M02: Job Posting'
      parameters:
        - in: path
          name: job_posting
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 'Ok. Show Edit Job UI'
    
  /job-postings/{job_posting}:
    put:
      operationId: R208
      summary: 'R208: Update Job Action'
      description: 'Process job update. Access: RCR'
      tags:
        - 'M02: Job Posting'
      parameters:
        - in: path
          name: job_posting
          required: true
          schema:
            type: integer
      responses:
        '302':
          description: 'Redirect after updating job.'
          headers:
            Location:
              schema:
                type: string
              examples:
                302Success:
                  description: 'Successful update. Redirect to job details.'
                  value: '/job_postings/{jobPosting}'
  
  /api:
    get:
      summary: 'API Status'
      description: 'Returns API status'
      tags:
        - 'M02: Job Posting'
      responses:
        '200':
          description: 'OK'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  version:
                    type: string
                  status:
                    type: string

  /job_postings/{jobPosting}/apply:
    post:
      operationId: R501
      summary: 'R501: Apply to Job'
      description: 'Submit application for a job. Access: JSK'
      tags:
        - 'M05: Job Applications'
      parameters:
        - in: path
          name: jobPosting
          required: true
          schema:
            type: integer
      requestBody:
        required: false
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                cover_letter:
                  type: string
                recommendation_letter:
                  type: string
      responses:
        '302':
          description: 'Redirect after applying.'
          headers:
            Location:
              schema:
                type: string
              examples:
                302Success:
                  description: 'Successful application. Redirect to job page.'
                  value: '/job_postings/{jobPosting}'
    get:
      operationId: R502
      summary: 'R502: Fill Form to Apply to Job'
      description: 'Provide UI to submit application for a job. Access: JSK'
      tags:
        - 'M05: Job Applications'
      parameters:
        - in: path
          name: jobPosting
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 'OK. Show Apply Form UI'

  /companies/{company}/edit:
    get:
      operationId: R601
      summary: 'R601: Edit Company Profile Form'
      description: 'Form to edit company info. Access: MNG'
      tags:
        - 'M06: Managers'
      parameters:
        - in: path
          name: company
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 'Ok. Show Company Edit UI'
  
  /companies/{company}: 
    get:
      operationId: R600
      summary: 'R600: View Company Profile'
      description: 'Show company profile. Access: PUB'
      tags:
        - 'M06: Managers'
      parameters:
        - in: path
          name: company
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 'Ok. Show Company Profile UI'
    put:
      operationId: R602
      summary: 'R602: Update Company Action'
      description: 'Process company info update. Access: MNG'
      tags:
        - 'M06: Managers'
      parameters:
        - in: path
          name: company
          required: true
          schema:
            type: integer
      responses:
        '302':
          description: 'Redirect after updating company.'
          headers:
            Location:
              schema:
                type: string
              examples:
                302Success:
                  description: 'Successful update. Redirect to company profile.'
                  value: '/companies/{company}'

  /admin/jobs:
    get:
      operationId: R701
      summary: 'R701: Manage Job Postings'
      description: 'Admin view to approve or remove jobs. Access: ADM'
      tags:
        - 'M07: User Administration and Static pages'
      responses:
        '200':
          description: 'Ok. Show Admin Jobs UI'

  /admin/content:
    get:
      operationId: R702
      summary: 'R702: Manage Content'
      description: 'Admin view to review content. Access: ADM'
      tags:
        - 'M07: User Administration and Static pages'
      responses:
        '200':
          description: 'Ok. Show Content Management UI'

  /admin/pages:
    get:
      operationId: R703
      summary: 'R703: Edit Platform Info'
      description: 'Admin view to edit static pages. Access: ADM'
      tags:
        - 'M07: User Administration and Static pages'
      responses:
        '200':
          description: 'Ok. Show Pages Edit UI'

  /about-us:
    get:
      operationId: R704
      summary: 'R704: View About Us Page'
      description: 'Public view of the About Us static page. Access: PUB'
      tags:
        - 'M07: User Administration and Static pages'
      responses:
        '200':
          description: 'Ok. Show About Us Page'

  /terms-of-service:
    get:
      operationId: R705
      summary: 'R705: View Terms of Service Page'
      description: 'Public view of the Terms of Service static page. Access: PUB'
      tags:
        - 'M07: User Administration and Static pages'
      responses:
        '200':
          description: 'Ok. Show Terms of Service Page'

  /privacy-policy:
    get:
      operationId: R706
      summary: 'R706: View Privacy Policy Page'
      description: 'Public view of the Privacy Policy static page. Access: PUB'
      tags:
        - 'M07: User Administration and Static pages'
      responses:
        '200':
          description: 'Ok. Show Privacy Policy Page'
